### ISSUE TITLE
Document Magic numbers

### ISSUE THREAD

**Issue by Xaseron** [ExpediaGroup/jenkins-spock#13]
Desired Behavior
==============================
`1 * getPipelineMock( "node" )("nodeType", _)`
What does the `1` tell me? It's horrible to read. I can't find anything in the GroovyDoc except for some examples.
I played around and it looks like the number of invocations of this step. Maybe an Enum with speaking names like Once, Never would be better.

Benefits
==============================

Please list the benefits of updating the project to have the new behavior, e.g.

1. Improve Readability

**Comment by ChriFo** [comment]
This framework uses the Spock test framework. Please read their documentation:

>  The cardinality of an interaction describes how often a method call is expected. 

Source: http://spockframework.org/spock/docs/1.2/interaction_based_testing.html#_cardinality

**Comment by Xaseron** [comment]
Thank you the clarifies it
