### ISSUE TITLE
Library is trying to create classes from resource files

### ISSUE THREAD

**Issue by ajrrjava** [ExpediaGroup/jenkins-spock#17]
Expected Behavior
==============================

The library should ignore resource files

Actual Behavior
==============================

The library is scanning all folders and tries to create classes from resource files.

Steps to Reproduce
==============================

1. Add a text file to the _main/resources_ folder
2. Run a Test
3. The scanner will read the text file and will try to create a class from the text file throwing several exceptions in the process

**Comment by awittha** [comment]
@ajrrjava , could you attach build output that shows the attempt to create a class file that you're talking about?

If this is coming from one of the classpath scanners - either `reflections` or `fast-classpath-scanner` - this is just how they work. Using a `logback.xml` file to control the verbosity of log output during a test-run (see the "examples" projects for examples) can suppress this output.

If you're seeing it come from somewhere else, I await a copy of the build output.

**Comment by awittha** [comment]
@ajrrjava , do you still require assistance with this issue?

**Comment by ajrrjava** [comment]
@awitta, thank you for your answer. The output I as seeing was coming from the scanners. Your proposed solution worked.
