### ISSUE TITLE
Mocking "env" var without a Jenkinsfile

### ISSUE THREAD

**Issue by flowerncsu** [ExpediaGroup/jenkins-spock#20]
I'm trying to mock the "env" var for a test which doesn't otherwise require a Jenkinsfile. Most of the examples and documentation I see uses getBinding().setVariable() on the Jenkinsfile, as discussed [in this issue](https://github.com/homeaway/jenkins-spock/issues/16).

I did see [this alternate method](https://github.com/homeaway/jenkins-spock/blob/master/src/test/groovy/com/homeaway/devtools/jenkins/testing/properties/JenkinsfileWithExplicitlyDefinedPropertySpec.groovy#L43) but when I use that, it still errors with `groovy.lang.MissingPropertyException: No such property: env for class: myClass` 

I've tried including the `explicitlyMockPipelineVariable("env")` line in the `setup()` function as shown in the example, as well as in a `setup:` clause within the test itself. Both attempts result in the same error.

**Comment by awittha** [comment]
Choosing `env` as the variable name for that particular test was a poor choice; that isn't actually how one would mock the `env` variable that Jenkins creates. I should've chosen a name like `variableFromPluginThatIsntADependency` or `variableFromASharedLibrary`. I apologize for the confusion.

If you've got code that uses Jenkins' `env` variable, are you not loading it with `loadPipelineScriptForTest()` before testing it? If so, how are you loading it?

If your code is Jenkins pipeline code that expects to be run (eventually) as part of a Jenkins pipeline script, you should use `loadPipelineScriptForTest()` on the code ([it doesn't have to be named `Jenkinsfile`](https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/test/DefaultPipelineSpec.groovy#L12-L13)) and then you can `.getBinding().setVariable()`.

Is it possible to share examples of your code-under-test and your specifications so I can better-understand

**Comment by flowerncsu** [comment]
Sure. We've got a shared library that we're trying to test. There's no implementation inherent in it, as it's a collection of functions for use by other teams. As a result, we were hoping to unit test directly, without needing a Jenkinsfile. We can create a test Jenkinsfile if that's the only way to resolve the issue, but were hoping for a simpler solution. We're calling the utility directly from the test right now.

The function I'm currently working on testing: https://github.com/openshift/contra-hdsl/blob/development/src/org/centos/contra/Infra/Utils.groovy#L310

The branch with my WIP tests: https://github.com/openshift/contra-hdsl/tree/spock-tests

**Comment by flowerncsu** [comment]
Sure. We've got a shared library that we're trying to test. There's no implementation inherent in it, as it's a collection of functions for use by other teams. As a result, we were hoping to unit test directly, without needing a Jenkinsfile. We can create a test Jenkinsfile if that's the only way to resolve the issue, but were hoping for a simpler solution. We're calling the utility directly from the test right now.

The function I'm currently working on testing: https://github.com/openshift/contra-hdsl/blob/development/src/org/centos/contra/Infra/Utils.groovy#L310

The branch with my WIP tests: https://github.com/openshift/contra-hdsl/tree/spock-tests

**Comment by flowerncsu** [comment]
Was that any help, or should I just try to restructure my tests so that I use a jenkinsfile?

**Comment by awittha** [comment]
Whew! Holidays hit before I could respond originally. 

In short, try this: 

```
def infraUtils
def setup() {
    infraUtils = loadPipelineScriptForTest( "src/org/centos/contra/Infra/Utils.groovy" )
    infraUtils.getBinding().setVariable("env", ["foo": "bar"])
}
```

It looks like you'll have to refactor some of the tests (`infraUtils` is now an instance variable with a new value for each test, and cannot be `@Shared`), but the above is the idiom I'd use.

# Why?

@rpocase is on the right track that `loadPipelineScriptForTest(...)` doesn't have to load a `Jenkinsfile` - it's for loading _any_ groovy script that might be used at some point in a Jenkins pipeline.

@flowerncsu , the file https://github.com/openshift/contra-hdsl/blob/development/src/org/centos/contra/Infra/Utils.groovy#L310 is

1. Groovy
2. Devoid of a class definition
3. Not loaded as a "var" in the shared library

At runtime, how is this consumed? If it's always like this: https://github.com/openshift/contra-hdsl/blob/2f8088574aa09f3aaf118ef4ee26b2bf666e19c7/vars/deployInfra.groovy#L18 then Groovy will implicitly make it an instance of [`groovy.lang.Script`](http://docs.groovy-lang.org/latest/html/api/groovy/lang/Script.html). So it then is technically a _script_ used at some point during a Jenkins _pipeline_.

However, `env` is not a Pipeline extension point or variable, not really. It doesn't come from a `@Symbol`, `@Extension`, or `@Descriptor` annotation in Java source code (or it would already be mocked) - it's injected into the Groovy Script [`Binding`](http://docs.groovy-lang.org/latest/html/api/groovy/lang/Binding.html) of the Jenkins pipeline, by Jenkins.

To set up a test environment, what you need to do (in my opinion) isn't to _mock_ `env`, but to play the role of Jenkins in your test setup, and simply define it on the binding. If you load `Utils` as a script with `loadPipelineScriptForTest(...)`, this is quite easy!

**Comment by flowerncsu** [comment]
Odd. When I use
```infraUtils = loadPipelineScriptForTest( "src/org/centos/contra/Infra/Utils.groovy" )```
it seems to drop the `/` between `Infra` and `Utils.groovy`.
```groovy.util.ResourceException: Cannot open URL: file:/home/cmays/projects/contra-hdsl/target/test-classes/src/org/centos/contra/InfraUtils.groovy```

Out of curiosity, I looked to see what would happen if I dropped the `/` myself (ie, is it actually using that string or pulling it from somewhere else), and

```infraUtils = loadPipelineScriptForTest( "src/org/centos/contra/InfraUtils.groovy" )```
results in
```groovy.util.ResourceException: Cannot open URL: file:/home/cmays/projects/contra-hdsl/target/test-classes/src/org/centos/contraInfraUtils.groovy```
so it's clearly dropping whatever the last `/` is.

Any idea why?

**Comment by flowerncsu** [comment]
Nevermind, the missing `/` was just an output issue. The path was appending to "/target/test-classes" and once I added a "../../" to the beginning of my path, it worked fine. I wouldn't say I've got a functional test yet, but it's now admitting that `env` exists, so this particular issue is resolved and I can move forward with finishing the test.

**Comment by sandeshwani** [comment]
So if I want to load a file `"src/com/mytest/jenkins/pipeline/library/abc.groovy"` than it should be `loadPipelineScriptForTest("../../com/mytest/jenkins/pipeline/library/abc.groovy")` 
It's strange but works.
