### ISSUE TITLE
How to mock a library class

### ISSUE THREAD

**Issue by werne2j** [ExpediaGroup/jenkins-spock#23]
I have a custom step that imports a library class, instantiates the class and then calls a method from that class. In my test, i was wondering how i would mock that class.. 

vars/step.groovy
```
import com.example.Utils

def call(Map config=[:]){
    utils = new Utils()
    return utils.method()
}
```
Utils.groovy
```
package com.example

def method(param) {
    // Does a thing
}
```
StepSpec.groovy
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification
import com.example.Utils

public class StepSpec extends JenkinsPipelineSpecification {

    def step = null

    def setup() {
	step = loadPipelineScriptForTest("vars/step.groovy")
        // How do i mock Utils here so that i don't have to worry about what happens inside the 
        // Utils.method
    }

    def "will call step with passed command" () {
	when:
	    step("param")
	then:
	    assert true
    }
}
```

**Comment by awittha** [comment]
In this case, the class is "just a groovy class*", so you need to use Spock's techniques for intercepting a constructor and returning a mock (or spy) object. There's nothing specific to `jenkins-spock` here.

I believe this is the correct Spock documentation: http://spockframework.org/spock/docs/1.0/interaction_based_testing.html#MockingConstructors

You can either _stub the constructor_ to return a `mock(Utils.class)` _or_ globally stub the constructor to return a _Spy_.

Spies are (decorated) real objects that will actually call through to the real implementations _unless_ you stub an interaction.... so if you're looking to prevent implementations in `Utils` from running, that isn't what you want - just stub the constructor to return a mock `Utils`. Maybe

```groovy
def mockUtils = mock(Utils.class)
new Utils() >> mockUtils
```

(Disclaimer: I didn't test the above; refer to the official documentation & iterate on that!)

If you don't mind, please share what ends up working for you in this case! It seems that incorporating `Utils` classes into pipeline test suites is a common question folks have!

**Comment by werne2j** [comment]
You nailed it. I had to use GroovyMock and add in global because of the way the code was written but based of your help this is what i ended up using...
```groovy
mockUtils = GroovyMock(Utils.class, global: true)
new Utils() >> mockUtils
```
