### ISSUE TITLE
How to mock the call to copyArtifacts + readFile

### ISSUE THREAD

**Issue by lmilbaum** [ExpediaGroup/jenkins-spock#30]
I have a function which uses copyArtifacts to retrieve an artifact from another build, read the artifact content and execute upon the value.

How do I mock this use case? 

Thanks

**Comment by awittha** [comment]
In my opinion, I would just mock the reading of the artifact to return the contents you want.

Depending on how complex that file is, maybe have the file contents be an actual separate test resource, instead of inline'd in the unit test.
