### ISSUE TITLE
explicitlyMockPipelineStep is needed even with getPipelineMock

### ISSUE THREAD

**Issue by tnguyen14** [ExpediaGroup/jenkins-spock#38]
I'm not sure if my setup is incorrect or not (I tried to copy from the `examples` as much as possible), but in my `setup` block, before I could do `getPipelineMock`, I have to explicitly mock that pipeline step first. That doesn't seem to be the case in the example.

For instance, if I do

```groovy
setup:
  getPipelineMock('sh')([returnStdout: true, script: 'echo foo']) >> 'foo'
```

I will get this error:

```
java.lang.IllegalStateException:
There is no pipeline step mock for [sh].
        1. Is the name correct?
        2. Does the pipeline step have a descriptor with that name?
        3. Does that step come from a plugin? If so, is that plugin listed as a dependency in your pom.xml?
        4. If not, you may need to call explicitlyMockPipelineStep('sh') in your test's setup: block.
```

What I need to do instead is

```groovy
setup:
  explicitlyMockPIpelineStep('sh')
  getPipelineMock('sh')([returnStdout: true, script: 'echo foo']) >> 'foo'
```

What might I be missing here?

**Comment by awittha** [comment]
Can you share your project's `pom.xml` (or other dependency specification)? Going through the error checklist, 

```
1. Is the name correct?
2. Does the pipeline step have a descriptor with that name?
3. Does that step come from a plugin? If so, is that plugin listed as a dependency in your pom.xml?
4. If not, you may need to call explicitlyMockPipelineStep('sh') in your test's setup: block.
```

1. It's definitely the correct name.
2. The `sh` step definitely has a descriptor named `sh`.

3. It comes from a plugin - is the plugin listed as a dependency of your project's tests?

**Comment by tnguyen14** [comment]
The `pom.xml` file is at https://gist.github.com/tnguyen14/0ef1ac6ee2adc6f362108e5160f15c4a

What might be the plugin that I'm missing?

**Comment by awittha** [comment]
> ```xml
> <dependency>
> 	
> 	<groupId>org.jenkins-ci.plugins.workflow</groupId>
> 	<artifactId>workflow-durable-task-step</artifactId>
> 	<version>2.21</version>
> 	<scope>test</scope>
> </dependency>
> ```
> -- https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/pom.xml#L156-L162

For every pipeline step your pipeline code uses, you need to be sure the plugin that provides it is listed in your `pom.xml`. You can look up _most_ pipeline steps and find out which plugin provides them, here: https://jenkins.io/doc/pipeline/steps/

**Comment by tnguyen14** [comment]
Thanks. Do you know what plugin provides the `scm` variable?

**Comment by awittha** [comment]
Not off the top of my head.

However: `scm` is a regular Groovy variable that Jenkins sets in the pipeline script's Binding. `scm` is not a `@GlobalVariable` Pipeline Variable, so it won't be automatically mocked (so it's not necessary to add it as a dependency in order for a test to run).

If you have code that uses `scm`, you will need to create _either_ a regular Spock mock _or_ a dummy `scm` object, then set it as described in the "Defining Pipeline Variables" section of the ["Mock Pipeline Variables" documentation](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#defining-pipeline-variables).

```groovy
def setup() {
	Jenkinsfile = loadPipelineScriptForTest("/Jenkinsfile")
	
	def test_scm = ...
	
	Jenkinsfile.getBinding().setVariable( "scm", test_scm )
}
```

**Comment by awittha** [comment]
Depending on what your code will try to do with `scm`, it may be helpful to create a Spock mock from one of the concrete implementations of Jenkins' SCM API. 

For example, [`hudson.plugins.git.GitSCM`](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/GitSCM.java). Or, maybe the probable parent: [`hudson.scm.SCM`](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/scm/SCM.java).

```groovy
import hudson.scm.SCM
...
def setup() {
	Jenkinsfile = loadPipelineScriptForTest("/Jenkinsfile")
	
	def test_scm = Mock( SCM )
	
	Jenkinsfile.getBinding().setVariable( "scm", test_scm )
}
```

I think that _should_ work, and it looks like `SCM.java` is part of Jenkins core, so you won't even need to add a dependency.

**Comment by tnguyen14** [comment]
Thanks @awittha. Is the `Mock` function provided by Spock?

Also, is there a benefit to doing `Jenkinsfile.getBinding().setVariable( "scm", test_scm )`, vs just `explicitlyMockPipelineVariable('scm')`?

**Comment by awittha** [comment]
`setVariable(...)` creates a groovy variable with the value you provide - which should be whatever the test needs.

`explicitlyMockPipelineVariable(...)`creates a mock [`@GlobalVariable`](https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/GlobalVariable.java), and should only be used if that's the kind of mock you need. It exists because GlobalVariable mocks require more complex behavior than Spock supports out-of-the box.

**Comment by tnguyen14** [comment]
Thanks for the explanation.

In an effort to try and pull in more plugins to avoid doing the `explicitlyMockPipelineStep`, I pulled in `pipeline-model-definition` plugin.

But once I did that, all the tests that were passing now fail with this error:

```
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution
```

Do you know why that might be the case? Should that plugin be pulled in?

**Comment by awittha** [comment]
Which pipeline step(s) did your code use from that plugin?

**Comment by tnguyen14** [comment]
I have a list of steps (for both declarative and scripted pipelines) that I am explicitly mocking now. I was wondering if any of them would be taken care of by that plugin:

`echo`, `dir`, `deleteDir`, `disableConcurrentBuilds`, `timestamps`, `writeFile`, `pwd`, `out`, `withEnv`, **`properties` etc.

**Comment by awittha** [comment]
> You can look up most pipeline steps and find out which plugin provides them, here: https://jenkins.io/doc/pipeline/steps/

That list will show you which plugins provide which steps. Only add a plugin as a dependency if it provides a step that you're using!

**Comment by tnguyen14** [comment]
Thanks Austin. Will do that.

Do you know how I could mock out `scm` correctly to replace an existing code below?

```groovy
		explicitlyMockPipelineVariable('scm')
		getPipelineMock('scm.getUserRemoteConfigs')() >> [
			getPipelineMock('remoteConfig')
		]
```

I tried something along the way of

```groovy
def scm = Stub(SCM) {
  getuserRemoteConfigs() >> [getPipelineMock('rmoteConfig')]
}
Jenkinsfile.getBinding().setVariable('scm', scm)
```

but that didn't work.

**Comment by awittha** [comment]
You should only use `getPipelineMock()` for pipeline steps and GlobalVariables. SCM isn't one of those, and neither will the result of `getUserRemoteConfigs()` be one. You can probably just use _regular_ Spock mocks:

```groovy
import hudson.plugins.git.GitSCM
import hudson.plugins.git.UserRemoteConfig

def setup() {

	Jenkinsfile = loadPipelineScriptForTest("Jenkinsfile")
	
	def scm = Mock(GitSCM)
	def remote_config = Mock(UserRemoteConfig)
	def remote_configs = [ remote_config ]
	scm.getUserRemoteConfigs() >> remote_configs
	
	Jenkinsfile.getBinding().setVariable( "scm", scm )
}
```

The pipeline-specific steps that `jenkins-spock` introduces are _only_ for working with objects that Jenkins' pipeline DSL defines (steps & GlobalVariables). Regular values and classes should use the regular Spock mocking & testing idioms.

**Comment by tnguyen14** [comment]
Thanks for the explanation and code suggestion. Appreciate it. I'm new to Groovy and Spock, so still trying to pick it up.

**Comment by tnguyen14** [comment]
@awittha do you know what plugin I'd need for the `pipeline` step?

```
java.lang.IllegalStateException:
During a test, the pipeline step [pipeline] was called but there was no mock for it.
        1. Is the name correct?
        2. Does the pipeline step have a descriptor with that name?
        3. Does that step come from a plugin? If so, is that plugin listed as a dependency in your pom.xml?
        4. If not, you may need to call explicitlyMockPipelineStep('pipeline') in your test's setup: block.
        at testSuiteSpec.testSuite default(testSuiteSpec.groovy:25)
Caused by: groovy.lang.MissingMethodException: No signature of method: testSuite.(intercepted on instance [testSuite@1f03fba0] during test [testSuiteSpec@4527f70a]) pipeline() is applicable for argument types: (testSuite$_call_closure1) values: [testSuite$_call_closure1@4f0cab0a]
        at testSuiteSpec.testSuite default(testSuiteSpec.groovy:25)
```

**Comment by awittha** [comment]
The [Pipeline: Declarative](https://plugins.jenkins.io/pipeline-model-definition) plugin should be the one that provides the `pipeline { ... }` step.

However, please see the discussion in Issue #27 regarding `pipeline { ... }` - it will be _really hard_ to unit-test a declarative pipeline, because it's _not really code_.

**Comment by turboBasic** [comment]
> However: `scm` is a regular Groovy variable that Jenkins sets in the pipeline script's Binding. `scm` is not a `@GlobalVariable` Pipeline Variable, so it won't be automatically mocked (so it's not necessary to add it as a dependency in order for a test to run).
> 

Jenkins lists `scm` and `env` explicitly in _Global Variables_ section of their documentation ($JOB_URL/pipeline-syntax/globals).  This is quite confusing to differentiate globals vs bindings vs other stuff.   Some guidance how to differentiate them would be really helpful

**Comment by awittha** [comment]
This whole library should have a wiki of documentation; the nuances & examples have outgrown the GroovyDoc on the `JenkinsPipelineSpecification` class.

However, FWIW in a quick note, `scm` and `env` are the only ones I know of that are "special" in some way (writes to ENV sometimes go through to the host machine environment, for example; no other 'global' has this magic ability... which means writing and then reading a complex object to a property in `env` won't always work as expected, if that object doesn't nicely serialize into a shell/command-line 'environment' value...). So, those two would get special callouts in some part of the multi-page, categorized wiki documentation that should someday exist.
