### ISSUE TITLE
Testing parallel blocks

### ISSUE THREAD

**Issue by amit-o** [ExpediaGroup/jenkins-spock#39]
Hey,  

I'm trying to test a pipeline with parallel stages, e.g. 
`
parallel: 'lint' {
// ...
}, 'unit tests' {
//...
}
`

In the mocked invocations, I can see the mock for parallel - 
getPipelineMock("parallel").call(['lint':pythonApiPipeline$_call_closure1$_closure5@5f254608, 'Unit tests':pythonApiPipeline$_call_closure1$_closure6@2eeb0f9b)

But I cannot figure how to make the test actually perform the closures, as right now it skips them.
Any help would be appreciated.

**Comment by awittha** [comment]
jenkins-spock doesn't do this for you.

You would need to stub the parallel step, and iterate through its input map's keys, evaluating each one whose value was a closure, something like (probably pseudocode):

```groovy
setup:
    getPipelineMock("parallel")(_as Map) >> { _args ->
        _args.each { _key, _value -> 
            if( _value instanceof Closure ) {
                _value()
            }
        }
    }
}
```

I think it's defensible to argue that jenkins-spock should do this for you. jenkins-spock does do this for whenever a Mock object's final argument is a Closure (which is indicative of the Jenkins pipeline DSL syntactic sugar for "passing a body block to a step that takes one).

That code is here: https://github.com/homeaway/jenkins-spock/blob/master/src/main/groovy/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.groovy#L515-L520

In the short-term, you can try to turn the above pseudocode into real code and include it in the `setup:` of all your tests.

In the mid- to long-term, you could send a PR to `jenkins-spock` to add this functionality, or wait on us to get around to it.

# In either case,

would you please create a new, dedicated feature-request issue for `jenkins-spock` asking for the `parallel` step's closures to be executed automatically? Please use the "feature request" issue template.

**Comment by oswalpalash** [comment]
The pseudo-code from @awittha can be called this way :
```
mockDSL.parallel(_) >> { _args ->
            _args.each { Map _args2 ->
                _args2.each { _key, _value ->
                    if( _value instanceof Closure ) {
                        _value()
                    }
                }
            }
        }
```
Or however you're mocking your stages

**Comment by awittha** [comment]
Tracked further in #55
