### ISSUE TITLE
Unable to load global PSL

### ISSUE THREAD

**Issue by illegalnumbers** [ExpediaGroup/jenkins-spock#44]
Expected Behavior
==============================

Loads the file in the vars/ directory properly without removing a slash.
Actual Behavior
==============================
Cannot open URL: file:/path/to/target/test-classes/varsstep.groovy

Steps to Reproduce
==============================
The failing code is defined as:
    def step = loadPipelineScriptForTest("vars/step.groovy")

And my tree is defined as:

```
├── src
│   ├── dir
│   │   └── dir
│   │       └── dir
│   │           ├── StepClass.groovy
│   └── pipeline.gdsl
├── test
│   └── unit
│       └── groovy
│           └── net
│               └── inseng
│                   └── jenkins
│                       └── stepTest.groovy
└── vars
    ├── step.groovy
```

This shouldn't fail, and it shouldn't strip my path.

**Comment by illegalnumbers** [comment]
If I put a main/resources dir under src and make a copy of my step.groovy var then it will load properly with loadPipelineScriptForTest('/vars/step.groovy'). This is unexpected though, I would expect it to follow similar to the jenkinspipeline psl build system.

**Comment by illegalnumbers** [comment]
It also does not seem to respect adding to the classpath properly.

**Comment by awittha** [comment]
This _appears_ to be the same situations as in https://github.com/homeaway/jenkins-spock/issues/46 - could you take a look and see if it looks like its? If so, I can merge the conversation & work on a resolution in one place.

**Comment by illegalnumbers** [comment]
Yea this looks like the same issue, you can merge it. The suggested solution with a sourceSet also doesn't work (tried previously). I ended up having my gradle build just copy the files to the expected location to get it to build correctly, a pretty non-optimal workaround.

**Comment by awittha** [comment]
(see #46 )
