### ISSUE TITLE
Pipeline logic is not executed using groovy-cps

### ISSUE THREAD

**Issue by sparshev** [ExpediaGroup/jenkins-spock#45]
Hi Guys,

I'm trying to find a testing framework that actually can execute the pipeline logic in the same way as workflow-cps-plugin do to catch the next bug in jenkins pipelines: [JENKINS-59911](https://issues.jenkins-ci.org/browse/JENKINS-59911)

Expected Behavior
==============================

```
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running DefaultPipelineSpec
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.271 s - in DefaultPipelineSpec
[INFO] Running DeployerSpec
DEBUG: CPS results: null, 6
DEBUG: CPS results: null, 6
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.093 s - in DeployerSpec
...
```

According to the bug, the logic should print "null, 6" and CPS tests of JenkinsPipelineUnit is almost doing the job: jenkinsci/JenkinsPipelineUnit#159 - but contains a bug with `.find/.findAll` and the other closure-based functions and its CPS testing is useless on a complex pipelines.

Actual Behavior
==============================

```
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running DefaultPipelineSpec
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.271 s - in DefaultPipelineSpec
[INFO] Running DeployerSpec
DEBUG: CPS results: 6, 6
DEBUG: CPS results: 6, 6
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.093 s - in DeployerSpec
...
```
jenkins-spock printing "6, 6" - that could mean anything, but for sure it's not the expected behavior - because of the previously described issue in groovy-cps.

Steps to Reproduce
==============================

1. Modify shared-library example with the next changes:
    ```diff
    diff --git a/examples/shared-library/vars/Deployer.groovy b/examples/shared-library/vars/Deployer.groovy
    index 1e594fd..d399249 100644
    --- a/examples/shared-library/vars/Deployer.groovy
    +++ b/examples/shared-library/vars/Deployer.groovy
    @@ -1,6 +1,10 @@
     import com.example.SharedLibraryConstants
    
     def call( _env ) {
    +    def a = 4
    +    def b = 3
    +    a = b = 6
    +    System.out.println("DEBUG: CPS results: ${a}, ${b}")
    
         if( _env == "test" ) {
             sshagent(["test-ssh"]) {
    ```
2. Run mvn clean verify in examples/shared-library

Additional Information
==============================
It seems like jenkins-spock actually not using groovy-cps to execute the logic.

**Comment by awittha** [comment]
> It seems like jenkins-spock actually not using groovy-cps to execute the logic.

This is correct. For simplicity, [we don't CPS-transform the code](https://javadoc.io/static/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#mock-pipeline-execution).

This was a deliberate design choice: jenkins-spock is focused on _unit-testing_ pipeline code. That the pipeline DSL & Groovy code is CPS-transformed by Jenkins behind-the-scenes is an implementation detail that isn't relevant to whether the pipeline source code is correct or not.

To actually run Jenkins pipeline code, [jenkinsfile-runner](https://github.com/jenkinsci/jenkinsfile-runner) sounds better-suited - though I haven't used it and couldn't say whether it transforms its pipelines or not.

**Comment by natsen** [comment]
@awittha jenkins pipeline execution implementation has limitations/differences (https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/) from jenkins-spock test environment, it is useful if unit test framework can provide same limitations. 

I am interested in your thoughts on how easier it is to enable jenkins-spock to run cps transformed code and what needs to be done. 

From my understanding, After CPS transforming code, We would need to handle CPSCallableInvocation to be able to run CPS transformed code. Do you think this can be entirely done in jenkins-spock. Or does it need support from spock.
