### ISSUE TITLE
Cannot open URL when using loadPipelineScriptForTest

### ISSUE THREAD

**Issue by marcus-held** [ExpediaGroup/jenkins-spock#46]
Expected Behavior
==============================

I expect that the script can be loaded for a test when it's located in the `vars` folder

Actual Behavior
==============================

I receive the following exception:
```
groovy.util.ResourceException: Cannot open URL: file:/Volumes/Workspace/code/jenkins-library/target/test-classes/varscommonPipeline.groovy

	at groovy.util.GroovyScriptEngine.getResourceConnection(GroovyScriptEngine.java:410)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:552)
	at com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification.loadPipelineScriptForTest(JenkinsPipelineSpecification.groovy:730)
	at com.innogames.village.jenkins.pipeline.PipelineTest.setup(PipelineTest.groovy:10)
```

I load the pipeline the same way It's loaded in the examples:

```groovy
class PipelineTest extends JenkinsPipelineSpecification {

  def commonPipeline

  def setup() {
    commonPipeline = loadPipelineScriptForTest("vars/commonPipeline.groovy")
  }
}
```

Steps to Reproduce
==============================

See above

Additional Information
==============================

I use the project within a shared library which I build with gradle.

The following screenshot is showing the debugger at the place where it fails.
![Screenshot 2019-11-22 at 11 40 52](https://user-images.githubusercontent.com/5991815/69419559-fcd0a900-0d1c-11ea-934d-3adddb79e140.png)

The used groovy runtime is 2.4.15

**Comment by marcus-held** [comment]
I figured out that the problem is that my script was not on one of the classpaths defined in `loadPipelineScriptForTest`. So I created this PR https://github.com/homeaway/jenkins-spock/pull/47 that makes it customizable

**Comment by awittha** [comment]
Oh! I just thought of something I should've thought of in the beginning.

The default source locations _shouldn't need_ to be configured or overridden. They are where the build tool responsible for kicking off the tests should stage all appropriate resources.

In the case of Maven, for example, if you have files in `test/resources` that should be available on the classpath during a test... all you have to do is tell Maven that you've got resources in a non-standard location. This is done with the [`<testResources>` tag](https://maven.apache.org/ref/3.0.4/maven-model/maven.html#class_testResource) (see [example](https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/pom.xml#L281-L294)).

In the case of Gradle, which I am not familiar with, there _should_ be a similar mechanism. It looks like that is perhaps [sourceSet](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html) ? 

By doing this, your resources will end up on the classpath of whatever engine is running `jenkins-spock`, and it should just work.

That said, the default paths are very maven-centric. Can you share more information about your Gradle setup?

I'd like to put PR #47 on hold until we sort this out, as having the engine be responsible for putting classpath resources in the right place (as with `target/classes` and `target/test-classes`) is a far more-robust approach to having `jenkins-spock` itself have to search for files _on disk_.

**Comment by marcus-held** [comment]
I see your point and I spent the last couple of hours to investigate it, but I wasn't able to make it work yet. 
Unfortunately I don't find the time soon to investigate further, but I plan to look into that again next week.

**Comment by awittha** [comment]
> ... The suggested solution with a sourceSet also doesn't work (tried previously). I ended up having my gradle build just copy the files to the expected location to get it to build correctly, a pretty non-optimal workaround.
> -- @illegalnumbers (#44)

So maybe Gradle's built-in resource/classpath idioms are such that we _do_ need `jenkins-spock` to look at a new on-disk location.

**Comment by marcus-held** [comment]
He describes pretty much my experience. I also spoke with some colleagues (but they are also no experts with gradle) and none knew how to do it with gradle. Even if its possible it appears to be no prominent solution. So giving `jenkins-spock` the ability to read on another location might be the most helpful in this case.

**Comment by awittha** [comment]
As part of trying to add a working Gradle example, I stumbled across this `sourceSet` setup:

```groovy
sourceSets {
	main {
		groovy {
			srcDirs = ['src']
		}
		resources {
			srcDirs = ['vars', 'resources']
		}
	}
	test {
		groovy {
			srcDirs = ['test']
		}
	}
}
```

Unfortunately, further Gradle issues (see https://github.com/homeaway/jenkins-spock/issues/22 ) prevented me from getting to the point where I might _confirm_ whether or not this worked but I'll leave this here for the future so I don't forget.

**Comment by yx135790** [comment]
just incase someone is still interested
you can setup a task and copy script into the target directory

task copyVars (type: Copy) {
  from "$rootDir/vars"
  include '**/*.groovy'
  into "target/classes/vars"
}
