### ISSUE TITLE
Jenkins-spock should automatically execute parallel closure steps

### ISSUE THREAD

**Issue by amit-o** [ExpediaGroup/jenkins-spock#51]
Desired Behavior
==============================

Jenkins-spock should automatically execute parallel closure steps.

Benefits
==============================

Should allow the testing of pipelines containing parallel steps more easily without refactoring.

**Comment by oswalpalash** [comment]
```
mockDSL.parallel(_) >> { _args ->
            _args.each { Map _args2 ->
                _args2.each { _key, _value ->
                    if( _value instanceof Closure ) {
                        _value()
                    }
                }
            }
        }
```
Adding this to the setup stage can do the trick.

**Comment by awittha** [comment]
@amit-o, would you please take a look at https://github.com/homeaway/jenkins-spock/pull/55 and see if it works for you?

**Comment by awittha** [comment]
(tracked further in #55 )
