### ISSUE TITLE
Unable to mock the setting of an environment variable

### ISSUE THREAD

**Issue by soda480** [ExpediaGroup/jenkins-spock#52]
Attempting to test the following code:
```
def method5() {
    def item1 = env.ITEM1 ?: 'default'
    def item2 = "value-${item1}"
    env.setProperty('ITEM2', item2)
    item2
}
```
With the following unit test:
```
    def 'test method5'() {
        setup:
            explicitlyMockPipelineVariable('env')
            getPipelineMock('env.getProperty').call('ITEM1') >> 'item1Value'
        expect:
            myExample.method5() == 'value-item1Value'
```
I continue to get the following error:
```
groovy.lang.MissingPropertyException: No such property: ITEM2 for class: com.homeaway.devtools.jenkins.testing.PipelineVariableImpersonator
```
When testing it a bit differently using the following method:
```
    def 'test method5-2'() {
        setup:
            explicitlyMockPipelineVariable('env')
        when:
            myExample.method5()
        then:
            1 * getPipelineMock('env.getProperty').call('ITEM1') >> 'item1Value'
            1 * getPipelineMock('env.setProperty').call('ITEM2', 'value-item1Value')
    }
```
I get the same error.

I've successfully unit tested cases for retrieving environment variables, but code that includes setting using 'setProperty' fails with the error above.

I'm thinking the best route is to create my own mock object for environment, but I'm not sure what class to Mock i.e. what the Environment API class is in Groovy. 
```
            def mockEnv = Mock(Object)
            myExample.getBinding().setVariable('env', mockEnv)
```

Any advice is appreciated. Thanks.

**Comment by awittha** [comment]
I'm sorry it took so long to get back to you on this!

This is a common slip-up: "Pipeline Variable" does _not_ mean a variable in a pipeline, but specifically "The symbol name given to a Java class that has implemented Jenkins `GlobalVariable` extension point."

`env` is not that - it's just* a regular Groovy variable - so use `.setBinding(...)` on your `Script` to populate it, not `explicitlyMockPipelineVariable(...)`.

See a full explanation & discussion in this FAQ issue comment: https://github.com/homeaway/jenkins-spock/issues/20#issuecomment-452765199

**Comment by awittha** [comment]
The 2.1.0 release of jenkins-spock expanded the documentation for working with variables: https://javadoc.io/static/com.homeaway.devtools.jenkins/jenkins-spock/2.1.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#using-pipeline-variables
