### ISSUE TITLE
loadPipelineScriptForTest() from vars -> java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by mrnguyen4386** [ExpediaGroup/jenkins-spock#68]
I want to write a unit test for the following groovy script, but it got an error when ```loadPipelineScriptForTEst()```  is called to load the scripts from vars: 
```
ava.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution
```

```
def call( _shaId ) {
    print("Getting PR info for ${_shaId}")
    def stringPayload = null
    withCredentials([string(credentialsId: 'BITBUCKET_READ_TOKEN', variable: 'token')]){
        stringPayload = sh(script:"""curl -H 'Authorization: Bearer ${token}' -H 'Content-Type: application/json' ${BITBUCKET_URL}rest/api/latest/projects/${projects}/repos/${repos}/commits/${_shaId}/pull-requests""",
                           returnStdout: true).trim()
    }
    print(stringPayload)
}
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class GetPullRequestInfoSpec extends JenkinsPipelineSpecification {

    def PrInfo = null

    def setup(){
        PrInfo = loadPipelineScriptForTest("vars/getPullRequestInfo.groovy")
    }
    
    def "No Pull Request"(){
        
    }
}

```

**Comment by awittha** [comment]
Could you please provide the full stack trace for the exception?

**Comment by mrnguyen4386** [comment]
[stackTrace.txt](https://github.com/ExpediaGroup/jenkins-spock/files/4506371/stackTrace.txt)

**Comment by mrnguyen4386** [comment]
@awittha

**Comment by kevinm90** [comment]
Hi @mrnguyen4386 I have a similar issue. Could you maybe share how you fixed this? Thanks lot :-)

**Comment by mrnguyen4386** [comment]
@kevinm90 hmm...to be honest, I’m not really sure what I did to fixed the issue. The issue was fixed for me when I did a big refactor for the pom.xml. And somewhere in the refactoring fixed the issue. :( What is the scope for your ‘’’org.jenkinsci.plugins.workflow.steps’’’ dependency in your pom.xml?

**Comment by kevinm90** [comment]
Hi @mrnguyen4386 . I have also fixed it now. So for anyone else stumbling across this: For me it were the different versions I used for the jenkins-plugins in the pom. I have included a variable for it then and made sure I use the same version for all the different jenkins-plugins. Then it worked fine.
