### ISSUE TITLE
how to stub httpRequest from HTTP Request Plugin

### ISSUE THREAD

**Issue by corporate-gadfly** [ExpediaGroup/jenkins-spock#71]
Newbie to `jenkins-spock`, `spock` and `groovy`.

Need some help stubbing `httpRequest` from [HTTP Request Plugin](https://www.jenkins.io/doc/pipeline/steps/http_request/). The jar dependency is `org.jenkins-ci.plugins:http_request:1.8.26`.

My usage looks like:
```
class Http2 implements Serializable {
    def verify() {
        def response = httpRequest 'http://abc.com/def'
        echo "${response.content}"
    }
}
```
I have tried writing a spec like the following:
```
    def 'http2 mock response' () {
        given:
        Http2 http2 = new Http2()
        def response = [:]
        response.content = "{'text': 'json response'}"
        getPipelineMock('httpRequest.call')('http://abc.com/def') >> response

        when:
        http2.verify()

        then:
        1 * getPipelineMock('httpRequest')(*_)
    }
```
but I get the exception:
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'Mock for type 'Closure' named 'getPipelineMock("httpRequest")'' with class 'groovy.lang.Closure$$EnhancerByCGLIB$$cda1b554' to class 'com.homeaway.devtools.jenkins.testing.PipelineVariableImpersonator'

	at com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification.getPipelineMock(JenkinsPipelineSpecification.groovy:742)
```
Changing the `getPipelineMock` call to:
```
getPipelineMock('httpRequest')('http://abc.com/def') >> response

```
gives me the following stacktrace:
```
[2020-05-24 20:09:49,149](main)([]) DEBUG JenkinsPipelineSpecification - TEST FIXTURE intercepted & redirected a call:
	Test         : class com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification
	Note         : pipeline step 
	Via          : class ca.utoronto.easi.jenkins.Http2.methodMissing
	    (types)  : Class.methodMissing
	Invocation   : class ca.utoronto.easi.jenkins.Http2.httpRequest([http://abc.com/def])
	    (types)  : Class.httpRequest(Object[])
	Forwarded To : Mock for type 'Closure' named 'getPipelineMock("httpRequest")'.call(http://abc.com/def)
	    (types)  : Closure$$EnhancerByCGLIB$$cda1b554.call(String)


java.lang.NullPointerException: Cannot get property 'content' on null object
```
One slight twist is that I am on gradle, not maven.

Any help is appreciated.

**Comment by awittha** [comment]
First,

* ❌ `getPipelineMock('httpRequest.call')('http://abc.com/def') >> response`
* ✅ `getPipelineMock('httpRequest')('http://abc.com/def') >> response` 

`httpRequest` is a _pipeline step_ from a plugin, so it is just `getPipelineMock(...)` of the step's name. The `objectName.methodName` form is only used for _variables_.

Second,

Hard to say without the full stack trace of

> `java.lang.NullPointerException: Cannot get property 'content' on null object`

but I believe based on the call trace that you have encountered one of the quirks of Spock:

_You cannot stub a mock in `given`/`when` and also expect it in `then`._ You have to set up your stubbing and expectations for any given mock in the same block. See the ["Combining Mocking and Stubbing"](http://spockframework.org/spock/docs/1.0/interaction_based_testing.html) section of the Spock documentation.

Try

```groovy
...
given:
1 * getPipelineMock('httpRequest')('http://abc.com/def') >> response
```

**Comment by corporate-gadfly** [comment]
TY. Following works:
```groovy
class Http2Spec extends JenkinsPipelineSpecification {
    def 'http2 mock response' () {
        given:
        Http2 http2 = new Http2()
        def response = [:]
        response.content = "{'text': 'json response'}"
        1 * getPipelineMock('httpRequest')('http://abc.com/def') >> response

        when:
        http2.verify()

        then:
        1 * getPipelineMock('echo')('{\'text\': \'json response\'}')
    }
}
```
Please feel free to close the issue.
