### ISSUE TITLE
Unable to run example tests due to dependency resolution exception

### ISSUE THREAD

**Issue by davehunt** [ExpediaGroup/jenkins-spock#8]
Expected Behavior
==============================

The example tests to be executed.

Actual Behavior
==============================

<details>
  <summary>The build fails with the following output:</summary>

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------< com.example:jenkinsfile-test-shared-library >-------------
[INFO] Building jenkinsfile-test-shared-library 0.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.jenkins-ci.main:jenkins-core:jar:2.102 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins.workflow:workflow-step-api:jar:2.10 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins.workflow:workflow-cps:jar:2.36 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci:symbol-annotation:jar:1.10 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins.workflow:workflow-durable-task-step:jar:2.21 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins:slack:jar:2.3 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins:pipeline-stage-step:jar:2.3 is missing, no dependency information available
[WARNING] The POM for org.jenkins-ci.plugins:ssh-agent:jar:1.16 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/workflow/workflow-cps-global-lib/2.10/workflow-cps-global-lib-2.10.pom
[WARNING] The POM for org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:jar:2.10 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/workflow/workflow-cps-global-lib/2.10/workflow-cps-global-lib-2.10.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.053 s
[INFO] Finished at: 2018-09-20T08:03:00-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jenkinsfile-test-shared-library: Could not resolve dependencies for project com.example:jenkinsfile-test-shared-library:jar:0.0.0-SNAPSHOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-core:jar:2.102, org.jenkins-ci.plugins.workflow:workflow-step-api:jar:2.10, org.jenkins-ci.plugins.workflow:workflow-cps:jar:2.36, org.jenkins-ci:symbol-annotation:jar:1.10, org.jenkins-ci.plugins.workflow:workflow-durable-task-step:jar:2.21, org.jenkins-ci.plugins:slack:jar:2.3, org.jenkins-ci.plugins:pipeline-stage-step:jar:2.3, org.jenkins-ci.plugins:ssh-agent:jar:1.16, org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:jar:2.10: Failure to find org.jenkins-ci.main:jenkins-core:jar:2.102 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
make: *** [test] Error 1
```

</details>

Steps to Reproduce
==============================

Please include a numbered list of steps that other people can use to recreate the "Actual Behavior."

1. Install Maven (via brew)
2. Clone repo
3. `cd examples/shared-library` (similar failures in other directories)
4. `make test`

Additional Information
==============================

<details>
  <summary>sw_vers</summary>

```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

</details>

<details>
  <summary>mvn -v</summary>

```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

</details>

<details>
  <summary>java -version</summary>

```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

</details>

**Comment by awittha** [comment]
Looking at this portion of the build's output: 

```
[ERROR] Failed to execute goal on project jenkinsfile-test-shared-library: Could not resolve dependencies for project com.example:jenkinsfile-test-shared-library:jar:0.0.0-SNAPSHOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-core:jar:2.102, org.jenkins-ci.plugins.workflow:workflow-step-api:jar:2.10, org.jenkins-ci.plugins.workflow:workflow-cps:jar:2.36, org.jenkins-ci:symbol-annotation:jar:1.10, org.jenkins-ci.plugins.workflow:workflow-durable-task-step:jar:2.21, org.jenkins-ci.plugins:slack:jar:2.3, org.jenkins-ci.plugins:pipeline-stage-step:jar:2.3, org.jenkins-ci.plugins:ssh-agent:jar:1.16, org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:jar:2.10: Failure to find org.jenkins-ci.main:jenkins-core:jar:2.102 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

and and adding some line-breaks in reasonable places, you can see:

> [ERROR] Failed to execute goal on project jenkinsfile-test-shared-library: 
> 
> Could not resolve dependencies for project com.example:jenkinsfile-test-shared-library:jar:0.0.0-SNAPSHOT: 
> 
> The following artifacts could not be resolved: (list of JARs):
> 
> Failure to find org.jenkins-ci.main:jenkins-core:jar:2.102 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

With the key message being (emphasis added):

> **Failure** to find org.jenkins-ci.main:jenkins-core:jar:2.102 in https://repo.maven.apache.org/maven2 **was cached in the local repository,** resolution will not be reattempted until the update interval of central has elapsed or updates are forced

This suggests that the build that generated this message was _not_ the first run attempted on that machine - there was probably a prior run that failed due to some _other_ reason, and Maven cached that failure. The original run would've had an actionable error message.

Double-check you've got a working internet connection and nothing "unusual" in your Maven's `settings.xml` (proxy configuration, repository mirrors, etc), and then run the `mvn` commands to build the example projects again, but with the `-U` flag added, e.g. `mvn verify -U` - this will "force the updates" mentioned in the error message.

If this still fails, the error message will likely be different than this current "failure was cached" message - please report back with that message to proceed with the troubleshooting process.

**Comment by davehunt** [comment]
I had tried with `-U` but failed to do so when reporting this issue. Here's the output from `mvn -U clean verify`. Is this working for you?

> [ERROR] Failed to execute goal on project jenkinsfile-test-shared-library:
> 
> Could not resolve dependencies for project com.example:jenkinsfile-test-shared-library:jar:0.0.0-SNAPSHOT:
> 
> The following artifacts could not be resolved:
>
> org.jenkins-ci.main:jenkins-core:jar:2.102, org.jenkins-ci.plugins.workflow:workflow-step-api:jar:2.10, org.jenkins-ci.plugins.workflow:workflow-cps:jar:2.36, org.jenkins-ci:symbol-annotation:jar:1.10, org.jenkins-ci.plugins.workflow:workflow-durable-task-step:jar:2.21, org.jenkins-ci.plugins:slack:jar:2.3, org.jenkins-ci.plugins:pipeline-stage-step:jar:2.3, org.jenkins-ci.plugins:ssh-agent:jar:1.16, org.jenkins-ci.plugins.workflow:workflow-cps-global-lib:jar:2.10: Could not find artifact org.jenkins-ci.main:jenkins-core:jar:2.102 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by awittha** [comment]
That message helps.

`org.jenkins-ci.main:jenkins-core:jar:2.102` definitely exists: https://mvnrepository.com/artifact/org.jenkins-ci.main/jenkins-core/2.102 

But:

<img width="617" alt="screen shot 2018-09-25 at 10 14 54 am" src="https://user-images.githubusercontent.com/25155847/46024203-e2b12180-c0ab-11e8-962d-75d11cf784aa.png">

Oops! It's not _actually_ in maven-central; it's in the Jenkins Releases repository.

We should've included a `<repositories>` block in each of the `pom.xml` files (the main project pom probably needs it, too) to point to the Jenkins Releases repository as an additional artifact source.

We'll fix that.

**Comment by awittha** [comment]
Pull request that fixes this for all `pom.xml` files is coming; in the meantime, add this to any pom:

```xml
<repositories>
	<repository>
		<id>jenkins-releases</id>
		<name>Jenkins Releases</name>
		<url>http://repo.jenkins-ci.org/releases</url>
	</repository>
</repositories>
```

and that should unblock you in the interim.

**Comment by awittha** [comment]
@davehunt, would you mind checking out the branch in PR #10 and letting me know if that works for you?

**Comment by davehunt** [comment]
It works great, thanks @awittha! 😄
